// 店铺信息
export const SETSHOPINFO = 'SETSHOPINFO'

// 登录
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const SHOPINFO_SUCCESS = 'SHOPINFO_SUCCESS'
export const SHOPINFO_FAILURE = 'SHOPINFO_FAILURE'
export const LOGOUT_SHOP = 'LOGOUT_SHOP'
export const UPDATE_SHOP_SUCCESS = 'UPDATE_SHOP_SUCCESS'

// 订单管理
export const MINIFOOD_INIT_FOOD = 'MINIFOOD_INIT_FOOD'
export const MINIFOOD_ADD_FOOD = 'MINIFOOD_ADD_FOOD'
export const MINIFOOD_REDUCE_FOOD = 'MINIFOOD_REDUCE_FOOD'
export const MINIFOOD_CLEAR_FOOD = 'MINIFOOD_CLEAR_FOOD'
export const GET_MINIFOOD_LIST = 'GET_MINIFOOD_LIST'
export const CALC_MINIFOOD_QUANTITY = 'CALC_MINIFOOD_QUANTITY'
export const CALC_MINIFOOD_LIST_COUNT = 'CALC_MINIFOOD_LIST_COUNT'
// 桌台管理

//菜品管理

export const MEAL_ADD_MODAL = 'MEAL_ADD_MODAL'

